export const SET_ORDER_DATA = "SET_ORDER_DATA";
export const SET_ORDER_ERROR = "SET_ORDER_ERROR";
export const REMOVE_ORDER_ERROR = "REMOVE_ORDER_ERROR";
export const SET_ORDER_LOADING_START = "SET_ORDER_LOADING_START";
export const SET_ORDER_LOADING_STOP = "SET_ORDER_LOADING_STOP";
