export const SET_COORDS = "SET_COORDS";
export const DELETE_COORDS = "DELETE_COORDS";
export const SET_ADDRESSES_ERROR = "SET_ADDRESSES_ERROR";
export const REMOVE_ADDRESSES_ERROR = "REMOVE_ADDRESSES_ERROR";
