export const PUT_CREDENTIALS = "PUT_CREDENTIALS";
export const REMOVE_CREDENTIALS = "REMOVE_CREDENTIALS";
export const SET_ERROR_CREDENTIALS = "SET_ERROR_CREDENTIALS";
export const REMOVE_ERROR_CREDENTIALS = "REMOVE_ERROR_CREDENTIALS";
