export const PUT_CREDENTIALS = "PUT_CREDENTIALS";
export const REMOVE_CREDENTIALS = "REMOVE_CREDENTIALS";
export const SET_ERROR_CREDENTIALS = "SET_ERROR_CREDENTIALS";
export const REMOVE_ERROR_CREDENTIALS = "REMOVE_ERROR_CREDENTIALS";
export const SAVE_CREDENTIALS = "SAVE_CREDENTIALS";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
